// <auto-generated />
using System;
using LibraryManagementSystemAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystemAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20251115204941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9b5a5b0-643b-407e-8272-ed42192c4c14"),
                            Bio = "Nigerian novelist.",
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6658),
                            FirstName = "Chinua",
                            LastName = "Achebe",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6660)
                        },
                        new
                        {
                            Id = new Guid("b399d7f0-adb2-4a48-8cd3-08694c00f2d8"),
                            Bio = "Nigerian playwright.",
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6671),
                            FirstName = "Wole",
                            LastName = "Soyinka",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6671)
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b300d26-edcb-4bc3-b158-8dd6cbd42549"),
                            AuthorId = new Guid("d9b5a5b0-643b-407e-8272-ed42192c4c14"),
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6987),
                            GenreId = new Guid("2ee4f22b-477e-402e-b40e-6bc6e3948b99"),
                            ISBN = "9780385474542",
                            PublicationYear = 1958,
                            Title = "Things Fall Apart",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6987)
                        },
                        new
                        {
                            Id = new Guid("d30d3b36-39da-4120-848a-09e25372e4ad"),
                            AuthorId = new Guid("b399d7f0-adb2-4a48-8cd3-08694c00f2d8"),
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6993),
                            GenreId = new Guid("cdfec743-7e29-47ca-bd10-70ba89fdd262"),
                            ISBN = "9780393322996",
                            PublicationYear = 1975,
                            Title = "Death and the King's Horseman",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6993)
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ee4f22b-477e-402e-b40e-6bc6e3948b99"),
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6946),
                            Description = "Fictional works",
                            Name = "Fiction",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6946)
                        },
                        new
                        {
                            Id = new Guid("cdfec743-7e29-47ca-bd10-70ba89fdd262"),
                            CreatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6950),
                            Description = "Dramatic works",
                            Name = "Drama",
                            UpdatedOn = new DateTime(2025, 11, 15, 20, 49, 40, 89, DateTimeKind.Utc).AddTicks(6951)
                        });
                });

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Book", b =>
                {
                    b.HasOne("LibraryManagementSystemAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystemAPI.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystemAPI.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
